version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/loadtest

  # load-testing:
  #   build:
  #     context: .
  #     dockerfile: ./docker/test/Dockerfile
  #   container_name: load-testing
  #   depends_on:
  #     nest-api:
  #       condition: service_started
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/loadtest
